version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.9.0
    steps:
      - checkout
      - run: "npm install"
      - run: "npm run test"
workflows:
    example-workflow:
      jobs:
        - build_and_test