version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    docker:
      - image: cimg/node@17.9.0
    steps:
      - checkout
      - run: "npm run start"
workflows:
    example-workflow:
      jobs:
        - build_and_test